import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import ReactPlayer from 'react-player'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Alondra Delgado</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
        Hello world!
        </h1>

        {/* <img 
        src='./pictures/leah1.JPG'
        alt='Leah Bright Headshot'
        /> */}
        <p>Whether playing the powerful corporate attorney, crime boss or the loving wife, Alondra’s artistic style is intelligent, powerful and charismatic. </p>
        <div>
          <h2>Acting Reel</h2>
          <ReactPlayer url='https://www.youtube.com/watch?v=XVh8Q695rCo' />
          <button>View more video clips</button>
        </div>
        <h2>Headshots and Images </h2>
        <div>
        <Image
        src='/pictures/alondra1.png'
        alt='Alondra Headshot'
        width='225'
        height='300'/>
        <Image
        src='/pictures/alondra2.png'
        alt='Alondra Headshot'
        width='225'
        height='300'/>
        <Image
        src='/pictures/alondra3.png'
        alt='Alondra Headshot'
        width='225'
        height='300'/>
        <Image
        src='/pictures/alondra4.png'
        alt='Alondra Headshot'
        width='225'
        height='300'/>
       <Image
        src='/pictures/alondra5.png'
        alt='Alondra Headshot'
        width='225'
        height='300'/>
       <Image
        src='/pictures/alondra6.png'
        alt='Alondra Headshot'
        width='225'
        height='300'/>
        </div>
        <h2>Selected Credits</h2>
        <h3> Film and TV</h3>
        <h3>Theatre</h3>
        <button>Download CV</button>
        {/* <img /> */}
        <h2>Voiceover</h2>
        {/* <img /> */}
        <p>
        Sheldon is a two-time Emmy winning storyteller who has spent his entire adult life in front of the camera as a television news reporter.
        As an actor, he sees himself taking on a deeper form of storytelling.

        Sheldon’s devotion to acting is driven by a desire to do more, show more, and to live the lives and circumstances that confront each of us.

        In just one year, Sheldon has studied under HB Studio, Andrew Wood Acting Studio, the New York Performing Arts Academy, and The Actor’s Workshop. He’s now a student of Tom Kibbe, who studied directly under Stella Adler, Sanford Meisner and Lee Strasberg.

        He maintains a hunger to learn, explore and do the work.

        Within his first six months of formal training, Sheldon booked roles in the movie Thanks to Her and the episodic series No Joke.
        </p>

        {/* <img /> */}

        <p>I am a storyteller. It’s a role that gives me purpose. That’s why it’s been my lifelong vocation.
        I honed my storytelling skills as a television reporter, but now I’ve transitioned into a deeper realm of the art: acting.

        I enjoy the synergistic sensation of seeing, listening, feeling, speaking and moving — with profound meaning — as part of a storyline.

        When I deliver that package of creative art to an audience, then see its impact — it comes alive as power and beauty in the same breath.</p>
        
      </main>
    </>
  )
}